version: '3.7'
x-refs:
services:
  django:
    image: django-local:latest
    build:
      context: ./django
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: settings.env.dev
      AWS_PROFILE: ${AWS_PROFILE}
    ports:
      - 8000:8000
    volumes:
      - ${HOME}/.aws:/home/django/.aws
      - ./django:/opt/django
    depends_on:
      - postgres
  swaggerui:
    image: swaggerapi/swagger-ui:latest
    restart: always
    environment:
      API_URL: docs/openapi-schema.yml
    ports:
      - 8080:8080
    volumes:
      - ./django/docs:/usr/share/nginx/html/docs
  postgres:
    image: postgres:11.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql
networks:
  default:
    name: docker-django-net
volumes:
  pg-data:
